[package]
name = "prime-challenge"
version = "0.1.0"
authors = ["wraikny <writtenknown@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
lazy_static = "1.4.0"